In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import datasets

# Premise

\begin{equation*}
    y_n = \beta_0 + \beta_1 x_n^{(1)} + \beta_2 x_n^{(2)} + ... + \beta_D x_n^{(D)} + \epsilon_n
\end{equation*}

$$ 
    \textbf{x}_n =
        \begin{pmatrix}
            1 & x_n^{(1)} & x_n^{(2)} & ... & x_n^{(D)}
        \end{pmatrix}^T
$$

$$
    \beta =
        \begin{pmatrix}
        \beta_0 & \beta_1 & \beta_2 & ... & \beta_D
        \end{pmatrix}^T
$$
\begin{equation*}
    y_n = \beta^T \textbf{x}_n + \epsilon_n
\end{equation*}

## Loss Function

\begin{equation*}
    \mathcal{L}(\hat{\beta}) = \frac{1}{2} \sum_{n=1}^N (y_n - \hat{y}_n)^2 = \frac{1}{2} \sum_{n=1}^N (y_n - \beta^T \textbf{x}_n)^2 
\end{equation*} 

$$ 
    \textbf{y} =
        \begin{bmatrix}
            y_1 \\
            y_2 \\
            ... \\
            y_N \\
        \end{bmatrix}
$$
$$ 
    \textbf{X} =
        \begin{bmatrix}
            \textbf{x}_1^T \\
            \textbf{x}_2^T \\
            ... \\
            \textbf{x}_N^T \\
        \end{bmatrix}
$$

$$
    \hat{\textbf{y}} = \textbf{X} \hat{\beta}
$$
$$
    \mathcal{L}(\hat{\beta}) = \frac{1}{2} (\textbf{y} - \textbf{X} \hat{\beta})^T (\textbf{y} - \textbf{X} \hat{\beta})
$$

## Parameter Estimation
Minimising the loss function by taking partial derivatives

\begin{equation*}
    \frac{\partial \mathcal{L}(\hat{\beta})}{\partial \hat{\beta}} = \frac{\partial \frac{1}{2} (\textbf{y} - \textbf{X} \hat{\beta})^T (\textbf{y} - \textbf{X} \hat{\beta})}{\partial \hat{\beta}}
\end{equation*}

For a symmetric matrix I,

$$
\frac{\partial (\textbf{q} - \textbf{As})^T I (\textbf{q} - \textbf{As})}{\partial \textbf{s}} = -2\textbf{A}^T I (\textbf{q} - \textbf{As})
$$

Using the above formula gives us,
$$
\frac{\partial \mathcal{L}(\hat{\beta})}{\partial \hat{\beta}} = -\textbf{X}^T(\textbf{y} - \textbf{X} \hat{\beta})
$$
$$
0 = -\textbf{X}^T(\textbf{y} - \textbf{X} \hat{\beta})
$$
$$
0 = -\textbf{X}^T\textbf{y} + \textbf{X}^T\textbf{X} \hat{\beta})
$$

$$
\textbf{X}^T\textbf{X} \hat{\beta} = \textbf{X}^T\textbf{y}
$$
$$
\hat{\beta} = (\textbf{X}^T\textbf{X})^{-1}\textbf{X}^T\textbf{y}
$$

# Implementation

In [19]:
def estimate_parameters(X, y):
    
    # Adding intercept ones
    ones = np.ones(len(X)).reshape(len(X), 1)
    X = np.concatenate((ones, X), axis=1)
    
    # Calculating the inverse term
    XtX = np.dot(X.T, X)
    XtX_inverse = np.linalg.inv(XtX)
    
    # Calculating the second term
    Xty = np.dot(X.T, y)
    
    # Calculating the parameter vector
    beta_hat = np.dot(XtX_inverse, Xty)

    return beta_hat, X

In [7]:
def calculate_rmse(y, y_hat):
    squared_error = np.power(y - y_hat, 2)
    mean_squared_error = np.mean(squared_error)
    rmse = np.sqrt(mean_squared_error)
    return rmse

In [17]:
def predict(X, beta_hat):
    y_hat = np.dot(X, beta_hat)
    return y_hat

In [8]:
def calculate_r2(y, y_hat):
    rss = np.power(y - y_hat, 2).sum()
    mean_y = np.mean(y)
    tss = np.power(y - mean_y, 2).sum()
    r2 = 1 - rss/tss
    return r2

In [11]:
boston = datasets.load_boston()
X = boston.data
y = boston.target

In [20]:
beta_hat, X_with_intercept = estimate_parameters(X, y)
beta_hat

array([ 3.64594884e+01, -1.08011358e-01,  4.64204584e-02,  2.05586264e-02,
        2.68673382e+00, -1.77666112e+01,  3.80986521e+00,  6.92224640e-04,
       -1.47556685e+00,  3.06049479e-01, -1.23345939e-02, -9.52747232e-01,
        9.31168327e-03, -5.24758378e-01])

In [23]:
y_hat = predict(X_with_intercept, beta_hat)
y_hat[:5]

array([30.00384338, 25.02556238, 30.56759672, 28.60703649, 27.94352423])

In [24]:
rmse_scratch = calculate_rmse(y, y_hat)
rmse_scratch

4.679191295697282

In [25]:
r2_scratch = calculate_r2(y, y_hat)
r2_scratch

0.7406426641094094

In [26]:
regressor = LinearRegression()
regressor.fit(X, y)

LinearRegression()

In [27]:
predictions = regressor.predict(X)
predictions[:5]

array([30.00384338, 25.02556238, 30.56759672, 28.60703649, 27.94352423])

In [31]:
rmse_sk = np.sqrt(mean_squared_error(y, predictions))
rmse_sk

4.679191295697281

In [32]:
r2_sk = r2_score(y, predictions)
r2_sk

0.7406426641094095